### ISSUE TITLE
"Getting started" error?

### ISSUE THREAD

**Issue by huggre** [iota-community/python-iota-workshop#1]
Dave

Is this correct:?
"cd python iota-workshop"

Should it not be:?
"cd python-iota-workshop

Is it possible to include the .py files so that i can view them directly from the Github repository?

Updated***
Found the .py files under Repl.it so NP

Hugo

**Comment by fijter** [comment]
Hey Hugo,

That was indeed a typo, and the code directory got removed by accident on my latest commit, it has been restored. Thank you for letting me know!
